# Imagen base de Node.js
FROM node:20-alpine

# Carpeta de trabajo
WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar solo dependencias de producción
RUN npm install --production

# Copiar el resto del código
COPY . .

# Exponer el puerto de Nómina
EXPOSE 3004

# Comando para iniciar
CMD ["npm", "start"]